export const numberToImageMap = new Map();
numberToImageMap.set(0,"/assets/photo/small/dorutu_small.png")
numberToImageMap.set(1,"/assets/photo/small/parva_small.png")
numberToImageMap.set(2,"/assets/photo/small/jula_small.png")
numberToImageMap.set(3,"/assets/photo/small/birsan_small.png")
numberToImageMap.set(4,"/assets/photo/small/kevin_small.png")
numberToImageMap.set(5,"/assets/photo/small/ghebrea_small.png")
numberToImageMap.set(6,"/assets/photo/small/cata_small.png")
numberToImageMap.set(7,"/assets/photo/small/edi_small.png")
numberToImageMap.set(8,"/assets/photo/small/omi_small.png")
numberToImageMap.set(9,"/assets/photo/small/masashi_small.png")
numberToImageMap.set(10,"/assets/photo/small/sasu_small.png")
numberToImageMap.set(11,"/assets/photo/small/matasaru_small.png")
numberToImageMap.set(12,"/assets/photo/small/iordache_small.png")
numberToImageMap.set(13,"/assets/photo/small/malea_small.png")
numberToImageMap.set(14,"/assets/photo/small/denisa_small.png")

export const numberToLosingImageMap = new Map();
numberToLosingImageMap.set(0,"/assets/photo/big/birsan.png")
numberToLosingImageMap.set(1,"/assets/photo/big/edi.png")
numberToLosingImageMap.set(2,"/assets/photo/big/birsan.png")
numberToLosingImageMap.set(3,"/assets/photo/big/edi.png")
numberToLosingImageMap.set(4,"/assets/photo/big/birsan.png")
numberToLosingImageMap.set(5,"/assets/photo/big/edi.png")
numberToLosingImageMap.set(6,"/assets/photo/big/birsan.png")
numberToLosingImageMap.set(7,"/assets/photo/big/edi.png")
numberToLosingImageMap.set(8,"/assets/photo/big/birsan.png")
numberToLosingImageMap.set(9,"/assets/photo/big/edi.png")
numberToLosingImageMap.set(10,"/assets/photo/big/birsan.png")
numberToLosingImageMap.set(11,"/assets/photo/big/edi.png")
numberToLosingImageMap.set(12,"/assets/photo/big/birsan.png")
numberToLosingImageMap.set(13,"/assets/photo/big/edi.png")
numberToLosingImageMap.set(14,"/assets/photo/big/birsan.png")