export const numberToSoundListMap = new Map();
numberToSoundListMap.set(0, [ "/assets/sounds/heads/voice_dorutu_1.ogg",  "/assets/sounds/heads/voice_dorutu_2.ogg"])
numberToSoundListMap.set(1, ["/assets/sounds/heads/voice_parva_1.ogg","/assets/sounds/heads/voice_parva_2.ogg"])
numberToSoundListMap.set(2, ["/assets/sounds/heads/voice_jula_1.ogg","/assets/sounds/heads/voice_jula_1.ogg"])
numberToSoundListMap.set(3, ["/assets/sounds/heads/voice_birsan_1.ogg","/assets/sounds/heads/voice_birsan_2.ogg"])
numberToSoundListMap.set(4, ["/assets/sounds/heads/voice_kevin_1.ogg","/assets/sounds/heads/voice_kevin_2.ogg"])
numberToSoundListMap.set(5, ["/assets/sounds/heads/voice_ghebrea_1.ogg","/assets/sounds/heads/voice_ghebrea_2.ogg"])
numberToSoundListMap.set(6, ["/assets/sounds/heads/voice_cata_1.ogg","/assets/sounds/heads/voice_cata_2.ogg"])
numberToSoundListMap.set(7, ["/assets/sounds/heads/voice_edi_1.mp3","/assets/sounds/heads/voice_edi_2.mp3"])
numberToSoundListMap.set(8, ["/assets/sounds/heads/voice_omi_1.ogg","/assets/sounds/heads/voice_omi_1.ogg"])
numberToSoundListMap.set(9, ["/assets/sounds/heads/voice_masashi_1.ogg","/assets/sounds/heads/voice_masashi_2.ogg"])
numberToSoundListMap.set(10, ["/assets/sounds/heads/voice_sasu_1.ogg","/assets/sounds/heads/voice_sasu_2.ogg"])
numberToSoundListMap.set(11, ["/assets/sounds/heads/voice_matasaru_1.ogg","/assets/sounds/heads/voice_matasaru_2.ogg"])
numberToSoundListMap.set(12, ["/assets/sounds/heads/voice_iordache_1.ogg","/assets/sounds/heads/voice_iordache_2.ogg"])
numberToSoundListMap.set(13, ["/assets/sounds/heads/voice_malea_1.ogg","/assets/sounds/heads/voice_malea_2.ogg"])
numberToSoundListMap.set(14, ["/assets/sounds/heads/voice_denisa_1.ogg","/assets/sounds/heads/voice_denisa_2.ogg"])
