export const numberToImageMap = new Map();
numberToImageMap.set(0,"/assets/photo/winner/birsan.png")
numberToImageMap.set(1,"/assets/photo/winner/edi.png")
numberToImageMap.set(2,"/assets/photo/winner/birsan.png")
numberToImageMap.set(3,"/assets/photo/winner/edi.png")
numberToImageMap.set(4,"/assets/photo/winner/birsan.png")
numberToImageMap.set(5,"/assets/photo/winner/edi.png")
numberToImageMap.set(6,"/assets/photo/winner/birsan.png")
numberToImageMap.set(7,"/assets/photo/winner/edi.png")
numberToImageMap.set(8,"/assets/photo/winner/birsan.png")
numberToImageMap.set(9,"/assets/photo/winner/edi.png")
numberToImageMap.set(10,"/assets/photo/winner/birsan.png")
numberToImageMap.set(11,"/assets/photo/winner/edi.png")
numberToImageMap.set(12,"/assets/photo/winner/birsan.png")
numberToImageMap.set(13,"/assets/photo/winner/edi.png")
numberToImageMap.set(14,"/assets/photo/winner/birsan.png")
numberToImageMap.set(15,"/assets/photo/winner/edi.png")
numberToImageMap.set(16,"/assets/photo/winner/birsan.png")

export const numberToLosingImageMap = new Map();
numberToLosingImageMap.set(0,"/assets/photo/loser/birsan.png")
numberToLosingImageMap.set(1,"/assets/photo/loser/edi.png")
numberToLosingImageMap.set(2,"/assets/photo/loser/birsan.png")
numberToLosingImageMap.set(3,"/assets/photo/loser/edi.png")
numberToLosingImageMap.set(4,"/assets/photo/loser/birsan.png")
numberToLosingImageMap.set(5,"/assets/photo/loser/edi.png")
numberToLosingImageMap.set(6,"/assets/photo/loser/birsan.png")
numberToLosingImageMap.set(7,"/assets/photo/loser/edi.png")
numberToLosingImageMap.set(8,"/assets/photo/loser/birsan.png")
numberToLosingImageMap.set(9,"/assets/photo/loser/edi.png")
numberToLosingImageMap.set(10,"/assets/photo/loser/birsan.png")
numberToLosingImageMap.set(11,"/assets/photo/loser/edi.png")
numberToLosingImageMap.set(12,"/assets/photo/loser/birsan.png")
numberToLosingImageMap.set(13,"/assets/photo/loser/edi.png")
numberToLosingImageMap.set(14,"/assets/photo/loser/birsan.png")
numberToLosingImageMap.set(15,"/assets/photo/loser/edi.png")
numberToLosingImageMap.set(16,"/assets/photo/loser/birsan.png")